#!/bin/bash

# Copyright ⓒ 2016 Mattias Bengtsson
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with This program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>

# git-wip makes it easier to work with wip-branches

function _help-flag {
    [[ " ${@} " == *" --help "* ]] || [[ " ${@} " == *" -h "* ]]
}

function _select-commit {
    local IFS=$'\n'
    select commit in $(git --no-pager wip log --oneline); do
        echo "${commit}" | cut -f1 -d" "
        break
    done
}

function autosquash {
    if _help-flag "${@}"; then
        echo "Usage: git wip autosquash [rebase-flags]"
        echo
        echo "Short-hand for:"
        echo "  EDITOR=true git rebase -i --autosquash [rebase-flags] <rebase-point>"
    else
        EDITOR=true git rebase -i --autosquash "${@}" "$(rebase-point)"
    fi
}

function fixup {
    if _help-flag "${@}"; then
        echo "Usage: git wip fixup [commit-flags]"
        echo
        echo "Add a fixup commit to a previous commit."
    else
        local commit
        commit="$(_select-commit "$(rebase-point)")"
        git commit "${@}" --fixup=${commit}
    fi
}

function log {
    if _help-flag "${@}"; then
        echo "Usage: git wip log [log-flags]"
        echo
        echo "Short-hand for:"
        echo "  git log [log-flags] \"$(git wip rebase-point)\".."
    else
        git log "${@}" "$(rebase-point)"..
    fi
}

function reapply {
    if _help-flag "${@}"; then
        echo "Usage: git wip reapply [rebase-flags]"
        echo
        echo "Short-hand for:"
        echo "  git rebase -i [rebase-flags] \"$(git wip rebase-point)\""
    else
        git rebase -i "${@}" "$(rebase-point)"
    fi
}

function rebase-point {
    for ref in $(git rev-list --parents "HEAD"); do
        if [ "$(git branch --contains "${ref}" | wc -l)" -gt 1 ]; then
            echo "${ref}"
            return
        fi
    done
}

function squash {
    if _help-flag "${@}"; then
        echo "Usage: git wip squash [commit-flags]"
        echo
        echo "Add a squash commit to a previous commit."
    else
        local commit
        commit="$(_select-commit "$(rebase-point)")"
        git commit "${@}" --squash=${commit}
    fi
}

arg="${1}"
shift
case "${arg}" in
    autosquash|autos-quash)
        autosquash "${@}"
        ;;
    fixup)
        fixup "${@}"
        ;;
    log)
        log "${@}"
        ;;
    reapply)
        reapply "${@}"
        ;;
    rebase-point)
        rebase-point "${@}"
        ;;
    squash)
        squash "${@}"
        ;;
    *)
        echo "Usage: git wip [command] [<option>]"
        echo
        echo "  git wip helps you modify commits since the latest branch-point"
        echo "  All commands work only on the commits unique to this branch"
        echo
        echo "Commands:"
        echo "  autosquash          Automatically squash all squash! and fixup! commits"
        echo "  fixup               Add a fixup commit to a previous commit."
        echo "  log                 Show commit logs"
        echo "  reapply             Reapply all commits using an interactive rebase"
        echo "  rebase-point        Get the parent of the first commit unique for this branch"
        echo "  squash              Add a squash commit to a previous commit."
        exit 2
        ;;
esac
